 -- A report will be generated that shows a Pokemon’s base stats
USE pokemondb;
DROP PROCEDURE IF EXISTS base_stats_nature;

DELIMITER //
CREATE PROCEDURE base_stats_nature(IN POKEMON_NUM INT(11), POKEMON_NATURE INT(11))
BEGIN
	DECLARE HP, ATTACK, DEFENSE, SPECIAL_ATTACK, SPECIAL_DEFENSE, SPEED INT DEFAULT 0;
    DECLARE ATK_MULT, DEF_MULT, SP_ATK_MULT, SP_DEF_MULT, SPD_MULT FLOAT DEFAULT 0;
    DECLARE PKMN_NAME VARCHAR(255);
    DECLARE PKMN_NATURE VARCHAR(255);
    
    SET ATK_MULT = (SELECT STAT_MULTIPLIER FROM NATURE_STAT WHERE NATURE_ID = POKEMON_NATURE AND STAT_ID = 2);
    SET DEF_MULT = (SELECT STAT_MULTIPLIER FROM NATURE_STAT WHERE NATURE_ID = POKEMON_NATURE AND STAT_ID = 3);
    SET SP_ATK_MULT = (SELECT STAT_MULTIPLIER FROM NATURE_STAT WHERE NATURE_ID = POKEMON_NATURE AND STAT_ID = 4);
    SET SP_DEF_MULT = (SELECT STAT_MULTIPLIER FROM NATURE_STAT WHERE NATURE_ID = POKEMON_NATURE AND STAT_ID = 5);
    SET SPD_MULT = (SELECT STAT_MULTIPLIER FROM NATURE_STAT WHERE NATURE_ID = POKEMON_NATURE AND STAT_ID = 6);
    
    SET PKMN_NAME = (SELECT POKEMON_NAME FROM POKEMON WHERE
		             POKEMON_ID = POKEMON_NUM);
    SET PKMN_NATURE = (SELECT NATURE_NAME FROM NATURE WHERE
		             NATURE_ID = POKEMON_NATURE);                     
    SET HP = (SELECT STAT_VALUE FROM BASE_STAT WHERE
		     STAT_ID = 1 AND POKEMON_ID = POKEMON_NUM);
    SET ATTACK = (SELECT STAT_VALUE FROM BASE_STAT WHERE
		     STAT_ID = 2 AND POKEMON_ID = POKEMON_NUM) * IFNULL(ATK_MULT,1);
    SET DEFENSE = (SELECT STAT_VALUE FROM BASE_STAT WHERE
		     STAT_ID = 3 AND POKEMON_ID = POKEMON_NUM) * IFNULL(DEF_MULT,1);
    SET SPECIAL_ATTACK = (SELECT STAT_VALUE FROM BASE_STAT WHERE
		     STAT_ID = 4 AND POKEMON_ID = POKEMON_NUM) * IFNULL(SP_ATK_MULT,1);       
    SET SPECIAL_DEFENSE = (SELECT STAT_VALUE FROM BASE_STAT WHERE
		     STAT_ID = 5 AND POKEMON_ID = POKEMON_NUM) * IFNULL(SP_DEF_MULT,1);
    SET SPEED = (SELECT STAT_VALUE FROM BASE_STAT WHERE
		     STAT_ID = 6 AND POKEMON_ID = POKEMON_NUM) * IFNULL(SPD_MULT,1);
             
	SELECT
    PKMN_NAME AS 'POKEMON',
    PKMN_NATURE AS 'NATURE',
    HP AS 'HP',
    ATTACK AS 'ATTACK',
    DEFENSE AS 'DEFENSE',
    SPECIAL_ATTACK AS 'SPECIAL_ATTACK',
    SPECIAL_DEFENSE AS 'SPECIAL_DEFENSE',
    SPEED AS 'SPEED';
END //
DELIMITER ;

CALL base_stats_nature(1,5)