DROP DATABASE IF EXISTS pokemondb;

CREATE DATABASE pokemondb;

USE pokemondb;

CREATE TABLE NATURE
(
    NATURE_ID   INT,
    NATURE_NAME VARCHAR(255) NOT NULL,
    PRIMARY KEY (NATURE_ID)
) ENGINE = INNODB;

CREATE TABLE STAT
(
    STAT_ID   INT,
    STAT_NAME VARCHAR(255) NOT NULL,
    PRIMARY KEY (STAT_ID)
) ENGINE = INNODB;

CREATE TABLE EGG_GROUP
(
    EGG_GROUP_ID   INT,
    EGG_GROUP_NAME VARCHAR(255) NOT NULL,
    PRIMARY KEY (EGG_GROUP_ID)
) ENGINE = INNODB;

CREATE TABLE TYPE
(
    TYPE_ID        INT,
    TYPE_NAME      VARCHAR(255) NOT NULL,
    TYPE_COLOR_HEX CHAR(6)      NOT NULL,
    PRIMARY KEY (TYPE_ID)
) ENGINE = INNODB;

CREATE TABLE TYPE_EFFECTIVENESS
(
    ATTACK_TYPE_ID           INT,
    DEFEND_TYPE_ID           INT,
    EFFECTIVENESS_MULTIPLIER FLOAT NOT NULL,
    PRIMARY KEY (ATTACK_TYPE_ID, DEFEND_TYPE_ID),
    FOREIGN KEY (ATTACK_TYPE_ID) REFERENCES TYPE (TYPE_ID),
    FOREIGN KEY (DEFEND_TYPE_ID) REFERENCES TYPE (TYPE_ID)
) ENGINE = INNODB;

CREATE TABLE ABILITY
(
    ABILITY_ID     INT,
    ABILITY_NAME   VARCHAR(255) NOT NULL,
    ABILITY_EFFECT TEXT         NOT NULL,
    PRIMARY KEY (ABILITY_ID)
) ENGINE = INNODB;

CREATE TABLE POKEMON
(
    POKEMON_ID          INT,
    POKEMON_NAME        VARCHAR(255) NOT NULL,
    POKEMON_DESCRIPTION TEXT         NOT NULL,
    POKEMON_IMAGE_URL   VARCHAR(255) NOT NULL,
    PRIMARY_TYPE        INT          NOT NULL,
    SECONDARY_TYPE      INT,
    PRIMARY_EGG_GROUP   INT          NOT NULL,
    SECONDARY_EGG_GROUP INT,
    PRIMARY_ABILITY     INT          NOT NULL,
    SECONDARY_ABILITY   INT,
    HIDDEN_ABILITY      INT,
    PRIMARY KEY (POKEMON_ID),
    FOREIGN KEY (PRIMARY_TYPE) REFERENCES TYPE (TYPE_ID),
    FOREIGN KEY (SECONDARY_TYPE) REFERENCES TYPE (TYPE_ID),
    FOREIGN KEY (PRIMARY_EGG_GROUP) REFERENCES EGG_GROUP (EGG_GROUP_ID),
    FOREIGN KEY (SECONDARY_EGG_GROUP) REFERENCES EGG_GROUP (EGG_GROUP_ID),
    FOREIGN KEY (PRIMARY_ABILITY) REFERENCES ABILITY (ABILITY_ID),
    FOREIGN KEY (SECONDARY_ABILITY) REFERENCES ABILITY (ABILITY_ID),
    FOREIGN KEY (HIDDEN_ABILITY) REFERENCES ABILITY (ABILITY_ID)
) ENGINE = INNODB;

CREATE TABLE BASE_STAT
(
    STAT_ID    INT,
    POKEMON_ID INT,
    STAT_VALUE INT NOT NULL,
    PRIMARY KEY (STAT_ID, POKEMON_ID),
    FOREIGN KEY (STAT_ID) REFERENCES STAT (STAT_ID),
    FOREIGN KEY (POKEMON_ID) REFERENCES POKEMON (POKEMON_ID)
) ENGINE = INNODB;

CREATE TABLE EVOLUTION_METHOD
(
    POKEMON_ID         INT,
    EVOLVES_INTO_ID    INT,
    METHOD_DESCRIPTION TEXT NOT NULL,
    PRIMARY KEY (POKEMON_ID, EVOLVES_INTO_ID),
    FOREIGN KEY (POKEMON_ID) REFERENCES POKEMON (POKEMON_ID),
    FOREIGN KEY (EVOLVES_INTO_ID) REFERENCES POKEMON (POKEMON_ID)
) ENGINE = INNODB;

CREATE TABLE ALTERNATE_FORM
(
    ALTERNATE_FORM_ID          INT AUTO_INCREMENT,
    POKEMON_ID                 INT,
    ALTERNATE_FORM_NAME        VARCHAR(255) NOT NULL,
    ALTERNATE_FORM_IMAGE_URL   VARCHAR(255) NOT NULL,
    PRIMARY KEY (ALTERNATE_FORM_ID, POKEMON_ID),
    FOREIGN KEY (POKEMON_ID) REFERENCES POKEMON (POKEMON_ID)
) ENGINE = INNODB;

CREATE TABLE NATURE_STAT
(
    NATURE_ID       INT,
    STAT_ID         INT,
    STAT_MULTIPLIER FLOAT NOT NULL,
    PRIMARY KEY (NATURE_ID, STAT_ID),
    FOREIGN KEY (NATURE_ID) REFERENCES NATURE (NATURE_ID),
    FOREIGN KEY (STAT_ID) REFERENCES STAT (STAT_ID)
) ENGINE = INNODB;
