-- A report will be generated for each Pokemon regarding with a list of which Pokemon it can breed with, using egg group data.
USE pokemondb;
DROP PROCEDURE IF EXISTS egg_group_compatibility;

DELIMITER //
CREATE PROCEDURE egg_group_compatibility(IN POKEMON_NUM INT(11))
BEGIN
	SELECT
		POKEMON.POKEMON_NAME AS "POKEMON",
		PRIMARY_GROUP.EGG_GROUP_NAME AS "PRIMARY EGG GROUP",
		SECONDARY_GROUP.EGG_GROUP_NAME AS "SECONDARY EGG GROUP"
    FROM POKEMON
		INNER JOIN EGG_GROUP AS PRIMARY_GROUP
			ON (PRIMARY_GROUP.EGG_GROUP_ID=POKEMON.PRIMARY_EGG_GROUP)
		INNER JOIN EGG_GROUP AS SECONDARY_GROUP
			ON (SECONDARY_GROUP.EGG_GROUP_ID=POKEMON.SECONDARY_EGG_GROUP)
    ORDER BY POKEMON_NUM;
END //
DELIMITER ;

call egg_group_compatibility(10)