-- A report will be generated of a Pokemon that will detail how moves of a given type will be effective against that Pokemon.
USE pokemondb;
DROP PROCEDURE IF EXISTS pokemon_type_effectiveness;

DELIMITER //
CREATE PROCEDURE pokemon_type_effectiveness(IN POKEMON_NUM INT(11))
BEGIN
    DECLARE PKMN_TYPE VARCHAR(255) DEFAULT NULL;
    DECLARE TYPE1, TYPE2 INT DEFAULT 0;
	DECLARE EFFECT1, EFFECT2, AVG_EFFECT INT(11);    
    
	SET TYPE1 = (SELECT PRIMARY_TYPE FROM POKEMON WHERE
			     POKEMON_ID = POKEMON_NUM);
	SET TYPE2 = (SELECT SECONDARY_TYPE FROM POKEMON WHERE
			     POKEMON_ID = POKEMON_NUM);
SELECT 
	PKMN_TYPE.TYPE_NAME AS "TYPES",
    TYPE_EFFECTIVENESS.EFFECTIVENESS_MULTIPLIER AS "EFFECTIVENESS"
    FROM TYPE_EFFECTIVENESS
    JOIN TYPE AS PKMN_TYPE
		ON (PKMN_TYPE.TYPE_ID=TYPE_EFFECTIVENESS.ATTACK_TYPE_ID)
	WHERE DEFEND_TYPE_ID = TYPE1 OR DEFEND_TYPE_ID = TYPE2;
END //
DELIMITER ;

CALL pokemon_type_effectiveness(1);


