USE pokemondb;

DROP PROCEDURE IF EXISTS remove_from_party;

DELIMITER //

CREATE PROCEDURE remove_from_party(IN IN_USERNAME VARCHAR(255), IN IN_POKEMON_ID INT)
BEGIN
    DECLARE RESOLVED_USERNAME VARCHAR(255) DEFAULT NULL;
    DECLARE RESOLVED_POKEMON_ID INT DEFAULT NULL;
    DECLARE POKEMON_ORDINAL INT DEFAULT NULL;

    START TRANSACTION;

    SET RESOLVED_USERNAME = (SELECT USERNAME FROM POKEDEX_USERS WHERE USERNAME = IN_USERNAME LIMIT 1);
    IF RESOLVED_USERNAME IS NOT NULL THEN
        SET RESOLVED_POKEMON_ID = (SELECT POKEMON_ID FROM POKEMON WHERE POKEMON_ID = IN_POKEMON_ID LIMIT 1);
        IF RESOLVED_POKEMON_ID IS NOT NULL THEN
            SET POKEMON_ORDINAL = (SELECT PARTY_ORDINAL
                                   FROM POKEMON_PARTY
                                   WHERE USERNAME = RESOLVED_USERNAME
                                     AND POKEMON_ID = RESOLVED_POKEMON_ID);
            IF POKEMON_ORDINAL IS NOT NULL THEN
                DELETE FROM POKEMON_PARTY WHERE USERNAME = RESOLVED_USERNAME AND POKEMON_ID = RESOLVED_POKEMON_ID;

                UPDATE POKEMON_PARTY
                SET PARTY_ORDINAL = PARTY_ORDINAL - 1
                WHERE USERNAME = RESOLVED_USERNAME
                  AND PARTY_ORDINAL > POKEMON_ORDINAL;

                COMMIT;
            ELSE
                ROLLBACK;
            END IF;
        ELSE
            ROLLBACK;
        END IF;
    ELSE
        ROLLBACK;
    END IF;
END //

DELIMITER ;
