--  A user can calculate type effectiveness by inputting the attacking type, and inputting the one or two defending types.
USE pokemondb;

DROP PROCEDURE IF EXISTS type_effectiveness;

DELIMITER //
CREATE PROCEDURE type_effectiveness(IN ATTACK_TYPE INT(11), DEFEND_TYPE_1 INT(11), DEFEND_TYPE_2 INT(11))
BEGIN
	DECLARE MAIN_TYPE, DEFEND1, DEFEND2 VARCHAR(255) DEFAULT 0;
    DECLARE EFFECT_VALUE1, EFFECT_VALUE2, AVG_EFFECT FLOAT DEFAULT 0;
    SET MAIN_TYPE = (SELECT TYPE_NAME FROM TYPE WHERE TYPE_ID = ATTACK_TYPE);
    SET DEFEND1 = (SELECT TYPE_NAME FROM TYPE WHERE TYPE_ID = DEFEND_TYPE_1);
    SET DEFEND2 = (SELECT TYPE_NAME FROM TYPE WHERE TYPE_ID = DEFEND_TYPE_2);
    SET EFFECT_VALUE1 = (SELECT EFFECTIVENESS_MULTIPLIER FROM TYPE_EFFECTIVENESS
		                 WHERE DEFEND_TYPE_ID = DEFEND_TYPE_1 AND ATTACK_TYPE_ID = ATTACK_TYPE);
	SET EFFECT_VALUE2 = (SELECT EFFECTIVENESS_MULTIPLIER FROM TYPE_EFFECTIVENESS
						 WHERE DEFEND_TYPE_ID = DEFEND_TYPE_2 AND ATTACK_TYPE_ID = ATTACK_TYPE);
    SET AVG_EFFECT = IFNULL(EFFECT_VALUE1,1) * IFNULL(EFFECT_VALUE2,1);

	SELECT
    MAIN_TYPE AS "ATTACKING",
    DEFEND1 AS "DEFENDING 1",
    DEFEND2 AS "DEFENDING 2",
    AVG_EFFECT AS "EFFECT";
END //
DELIMITER ;

CALL type_effectiveness(10,11,1)