USE pokemondb;
DROP PROCEDURE IF EXISTS get_by_type;

DELIMITER //
CREATE PROCEDURE get_by_2_type(IN TYPE1 INT(11), TYPE2 INT(11))
BEGIN
	SELECT
    POKEMON.POKEMON_NAME AS "POKEMON",
    TYPE_1.TYPE_NAME AS "TYPE 1",
    TYPE_2.TYPE_NAME AS "TYPE 2",
    POKEMON.POKEMON_DESCRIPTION AS "DESCRIPTION"
    FROM POKEMON
    JOIN TYPE AS TYPE_1
		ON (TYPE_1.TYPE_ID=POKEMON.PRIMARY_TYPE)
	JOIN TYPE AS TYPE_2
		ON (TYPE_2.TYPE_ID=POKEMON.SECONDARY_TYPE)
	WHERE POKEMON.PRIMARY_TYPE = TYPE1 AND (POKEMON.SECONDARY_TYPE = TYPE2);
END //

CREATE PROCEDURE get_by_1_type(IN TYPE1 INT(11))
BEGIN
	SELECT
    POKEMON.POKEMON_NAME AS "POKEMON",
    TYPE_1.TYPE_NAME AS "TYPE 1",
    POKEMON.POKEMON_DESCRIPTION AS "DESCRIPTION"
    FROM POKEMON
    JOIN TYPE AS TYPE_1
		ON (TYPE_1.TYPE_ID=POKEMON.PRIMARY_TYPE)
	WHERE POKEMON.PRIMARY_TYPE = TYPE1 AND POKEMON.SECONDARY_TYPE IS NULL;
END //

CALL get_by_2_type(1,3);
CALL get_by_1_type(12);