-- View base stats that are over 100
USE pokemondb;
-- HP
DROP VIEW IF EXISTS view_hp;
CREATE VIEW view_hp AS
SELECT POKEMON.POKEMON_NAME AS "NAME",
       BASE_STAT.STAT_VALUE AS "HP"
FROM BASE_STAT
	JOIN POKEMON
    ON (POKEMON.POKEMON_ID=BASE_STAT.POKEMON_ID)
WHERE BASE_STAT.STAT_ID = 1 AND BASE_STAT.STAT_VALUE > 100;

-- attack
DROP VIEW IF EXISTS view_attack;
CREATE VIEW view_attack AS
SELECT POKEMON.POKEMON_NAME AS "NAME",
       BASE_STAT.STAT_VALUE AS "ATTACK"
FROM BASE_STAT
	JOIN POKEMON
    ON (POKEMON.POKEMON_ID=BASE_STAT.POKEMON_ID)
WHERE BASE_STAT.STAT_ID = 2 AND BASE_STAT.STAT_VALUE > 100;

-- defense
DROP VIEW IF EXISTS view_defense;
CREATE VIEW view_defense AS
SELECT POKEMON.POKEMON_NAME AS "NAME",
       BASE_STAT.STAT_VALUE AS "DEFENSE"
FROM BASE_STAT
	JOIN POKEMON
    ON (POKEMON.POKEMON_ID=BASE_STAT.POKEMON_ID)
WHERE BASE_STAT.STAT_ID = 3 AND BASE_STAT.STAT_VALUE > 100;

-- special attack
DROP VIEW IF EXISTS view_special_attack;
CREATE VIEW view_special_attack AS
SELECT POKEMON.POKEMON_NAME AS "NAME",
       BASE_STAT.STAT_VALUE AS "SPECIAL ATTACK"
FROM BASE_STAT
	JOIN POKEMON
    ON (POKEMON.POKEMON_ID=BASE_STAT.POKEMON_ID)
WHERE BASE_STAT.STAT_ID = 4 AND BASE_STAT.STAT_VALUE > 100;

-- special defense
DROP VIEW IF EXISTS view_special_defense;
CREATE VIEW view_special_defense AS
SELECT POKEMON.POKEMON_NAME AS "NAME",
       BASE_STAT.STAT_VALUE AS "SPECIAL DEFENSE"
FROM BASE_STAT
	JOIN POKEMON
    ON (POKEMON.POKEMON_ID=BASE_STAT.POKEMON_ID)
WHERE BASE_STAT.STAT_ID = 5 AND BASE_STAT.STAT_VALUE > 100;

-- speed
DROP VIEW IF EXISTS view_speed;
CREATE VIEW view_speed AS
SELECT POKEMON.POKEMON_NAME AS "NAME",
       BASE_STAT.STAT_VALUE AS "SPEED"
FROM BASE_STAT
	JOIN POKEMON
    ON (POKEMON.POKEMON_ID=BASE_STAT.POKEMON_ID)
WHERE BASE_STAT.STAT_ID = 6 AND BASE_STAT.STAT_VALUE > 100;


SELECT * FROM pokemondb.view_hp;
SELECT * FROM pokemondb.view_attack;
SELECT * FROM pokemondb.view_defense;
SELECT * FROM pokemondb.view_special_attack;
SELECT * FROM pokemondb.view_special_defense;
SELECT * FROM pokemondb.view_speed;